In [1]:
import pandas as pd
from personal_api import verificar_registros
from personal_api import importar_datos

In [2]:
#pasando archivo de xls a xlsx
borrador_personal = pd.read_excel('C:/wamp64/www/cos/app/Scripts/personal/planilla_personal.xls')
borrador_personal.to_excel('planilla_personal.xlsx', index=False)

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
*** No CODEPAGE record, no encoding_override: will use 'iso-8859-1'

In [3]:
#leyendo el archivo y guardandolo en un dataframe
personal = pd.read_excel('C:/wamp64/www/cos/app/Scripts/personal/planilla_personal.xlsx')

#manteniendo solo las columnas necesarias
personal = personal[['legajo', 'nombres', 'apellido', 'fecha_ing', 'tipo_doc', 'nro_doc', 'convenio']]

In [4]:
personal = personal.rename(columns={'nombres': 'nombre'})

In [5]:
# config de la api
API_URL = "https://cos.cyhsur.com/api/personal"
API_KEY = "8fyKQKXigzy0qu9JttaKzrRlkF9Z0bmy0hm9KE1D012c5e1b"

In [10]:
API_URL2 = "http://localhost:8000/api/personal/verificar"

In [8]:
# resultado = importar_datos(personal, API_URL, API_KEY)
# print(resultado['message'])

In [9]:
personal.head()

,legajo,nombre,apellido,fecha_ing,tipo_doc,nro_doc,convenio
0,1,GUILLERMO MARTIN,TORO,2019-03-25,DU,18365141,CONVENIO SEGURIDAD
1,3,NESTOR,ISADOR,2019-06-18,DU,21915520,CONVENIO SEGURIDAD
2,5,GUIDO,LOPARDO*,2008-11-06,DU,12345678,CONVENIO SEGURIDAD
3,6,NELSON,FLANDERS,2013-03-12,DU,29901081,CONVENIO SEGURIDAD
4,9,SEBASTIAN,RENDO,2012-07-10,DU,16315583,CONVENIO SEGURIDAD

In [ ]:
muestra = personal.head(2).copy()

nuevo_registro = {
    'legajo': 9999,  
    'nombre': 'LUCIA',
    'apellido': 'PARDINI', 
    'fecha_ing': '1800-12-12 00:00:00',
    'tipo_doc': 'DU',
    'nro_doc': '99999999',
    'convenio': 'CONVENIO TEST'
}

df = pd.DataFrame([nuevo_registro])

muestra_personal = pd.concat([muestra, df], ignore_index=True)
muestra_personal

,legajo,nombre,apellido,fecha_ing,tipo_doc,nro_doc,convenio
0,1,GUILLERMO MARTIN,TORO,2019-03-25 00:00:00,DU,18365141,CONVENIO SEGURIDAD
1,3,NESTOR,ISADOR,2019-06-18 00:00:00,DU,21915520,CONVENIO SEGURIDAD
2,9999,LUCIA,PARDINI,1800-12-12,DU,99999999,CONVENIO TEST

In [ ]:
resultados = verificar_registros(df=personal, api_url=API_URL2)
print(resultados)

{'success': True, 'estadisticas': {'total': 39, 'existentes': 39, 'nuevos': 0, 'errores': 0}, 'resultados': [{'indice': 0, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 15, 'nombre': 'GUILLERMO MARTIN', 'apellido': 'TORO', 'documento': None, 'fecha_ing': '2019-03-25', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '18365141', 'telefono': '', 'legajo': '1'}, 'datos_consultados': {'legajo': 1, 'nombre': 'GUILLERMO MARTIN', 'apellido': 'TORO', 'fecha_ing': '2019-03-25', 'tipo_doc': 'DU', 'nro_doc': '18365141', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 1, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 16, 'nombre': 'NESTOR', 'apellido': 'ISADOR', 'documento': None, 'fecha_ing': '2019-06-18', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '21915520', 'telefono': '', 'legajo': '3'}, 'datos_consultados': {'legajo': 3, 'nombre': 'NESTOR', 'apellido': 'ISADOR', 'fecha_ing': '2019-06-18', 'tipo_doc': 'DU', 'nro_doc': '21915520', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 2, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 17, 'nombre': 'GUIDO', 'apellido': 'LOPARDO*', 'documento': None, 'fecha_ing': '2008-11-06', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '12345678', 'telefono': '', 'legajo': '5'}, 'datos_consultados': {'legajo': 5, 'nombre': 'GUIDO', 'apellido': 'LOPARDO*', 'fecha_ing': '2008-11-06', 'tipo_doc': 'DU', 'nro_doc': '12345678', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 3, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 18, 'nombre': 'NELSON', 'apellido': 'FLANDERS', 'documento': None, 'fecha_ing': '2013-03-12', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '29901081', 'telefono': '', 'legajo': '6'}, 'datos_consultados': {'legajo': 6, 'nombre': 'NELSON', 'apellido': 'FLANDERS', 'fecha_ing': '2013-03-12', 'tipo_doc': 'DU', 'nro_doc': '29901081', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 4, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 19, 'nombre': 'SEBASTIAN', 'apellido': 'RENDO', 'documento': None, 'fecha_ing': '2012-07-10', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '16315583', 'telefono': '', 'legajo': '9'}, 'datos_consultados': {'legajo': 9, 'nombre': 'SEBASTIAN', 'apellido': 'RENDO', 'fecha_ing': '2012-07-10', 'tipo_doc': 'DU', 'nro_doc': '16315583', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 5, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 20, 'nombre': 'CRISTIAN', 'apellido': 'OSHIRO', 'documento': None, 'fecha_ing': '2002-07-10', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '40396257', 'telefono': '', 'legajo': '10'}, 'datos_consultados': {'legajo': 10, 'nombre': 'CRISTIAN', 'apellido': 'OSHIRO', 'fecha_ing': '2002-07-10', 'tipo_doc': 'DU', 'nro_doc': '40396257', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 6, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 21, 'nombre': 'LEANDRO', 'apellido': 'LAPIANA', 'documento': None, 'fecha_ing': '2010-01-01', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '11321796', 'telefono': '', 'legajo': '11'}, 'datos_consultados': {'legajo': 11, 'nombre': 'LEANDRO', 'apellido': 'LAPIANA', 'fecha_ing': '2010-01-01', 'tipo_doc': 'DU', 'nro_doc': '11321796', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 7, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 22, 'nombre': 'ALEJANDRO', 'apellido': 'ACOMPAIRED', 'documento': None, 'fecha_ing': '2010-01-01', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '17707275', 'telefono': '', 'legajo': '12'}, 'datos_consultados': {'legajo': 12, 'nombre': 'ALEJANDRO', 'apellido': 'ACOMPAIRED', 'fecha_ing': '2010-01-01', 'tipo_doc': 'DU', 'nro_doc': '17707275', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 8, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 23, 'nombre': 'NILDA NOEMI', 'apellido': 'SANCHEZ', 'documento': None, 'fecha_ing': '2008-09-12', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '31091150', 'telefono': '', 'legajo': '13'}, 'datos_consultados': {'legajo': 13, 'nombre': 'NILDA NOEMI', 'apellido': 'SANCHEZ', 'fecha_ing': '2008-09-12', 'tipo_doc': 'DU', 'nro_doc': '31091150', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 9, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 24, 'nombre': 'MELISA', 'apellido': 'TEMPER', 'documento': None, 'fecha_ing': '2010-01-01', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '39800877', 'telefono': '', 'legajo': '14'}, 'datos_consultados': {'legajo': 14, 'nombre': 'MELISA', 'apellido': 'TEMPER', 'fecha_ing': '2010-01-01', 'tipo_doc': 'DU', 'nro_doc': '39800877', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 10, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 25, 'nombre': 'MARIANA', 'apellido': 'TORRES', 'documento': None, 'fecha_ing': '2012-12-01', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '37864085', 'telefono': '', 'legajo': '15'}, 'datos_consultados': {'legajo': 15, 'nombre': 'MARIANA', 'apellido': 'TORRES', 'fecha_ing': '2012-12-01', 'tipo_doc': 'DU', 'nro_doc': '37864085', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 11, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 26, 'nombre': 'SILVINA', 'apellido': 'ZAJOUR', 'documento': None, 'fecha_ing': '2012-10-01', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '34626180', 'telefono': '', 'legajo': '16'}, 'datos_consultados': {'legajo': 16, 'nombre': 'SILVINA', 'apellido': 'ZAJOUR', 'fecha_ing': '2012-10-01', 'tipo_doc': 'DU', 'nro_doc': '34626180', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 12, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 27, 'nombre': 'TOMAS', 'apellido': 'GARCIA', 'documento': None, 'fecha_ing': '2010-01-01', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '37864041', 'telefono': '', 'legajo': '17'}, 'datos_consultados': {'legajo': 17, 'nombre': 'TOMAS', 'apellido': 'GARCIA', 'fecha_ing': '2010-01-01', 'tipo_doc': 'DU', 'nro_doc': '37864041', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 13, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 28, 'nombre': 'CANDELA', 'apellido': 'GUTIERREZ', 'documento': None, 'fecha_ing': '2012-01-01', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '28879860', 'telefono': '', 'legajo': '18'}, 'datos_consultados': {'legajo': 18, 'nombre': 'CANDELA', 'apellido': 'GUTIERREZ', 'fecha_ing': '2012-01-01', 'tipo_doc': 'DU', 'nro_doc': '28879860', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 14, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 29, 'nombre': 'PABLO', 'apellido': 'GARCIA', 'documento': None, 'fecha_ing': '2012-11-05', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '24478791', 'telefono': '', 'legajo': '19'}, 'datos_consultados': {'legajo': 19, 'nombre': 'PABLO', 'apellido': 'GARCIA', 'fecha_ing': '2012-11-05', 'tipo_doc': 'DU', 'nro_doc': '24478791', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 15, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 30, 'nombre': 'GRACIELA', 'apellido': 'MELIS', 'documento': None, 'fecha_ing': '2011-05-10', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '32823008', 'telefono': '', 'legajo': '20'}, 'datos_consultados': {'legajo': 20, 'nombre': 'GRACIELA', 'apellido': 'MELIS', 'fecha_ing': '2011-05-10', 'tipo_doc': 'DU', 'nro_doc': '32823008', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 16, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 31, 'nombre': 'HECTOR', 'apellido': 'PAEZ', 'documento': None, 'fecha_ing': '1999-04-10', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '22397574', 'telefono': '', 'legajo': '21'}, 'datos_consultados': {'legajo': 21, 'nombre': 'HECTOR', 'apellido': 'PAEZ', 'fecha_ing': '1999-04-10', 'tipo_doc': 'DU', 'nro_doc': '22397574', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 17, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 32, 'nombre': 'CLAUDIO', 'apellido': 'RITONDO', 'documento': None, 'fecha_ing': '2010-10-25', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '18028675', 'telefono': '', 'legajo': '22'}, 'datos_consultados': {'legajo': 22, 'nombre': 'CLAUDIO', 'apellido': 'RITONDO', 'fecha_ing': '2010-10-25', 'tipo_doc': 'DU', 'nro_doc': '18028675', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 18, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 33, 'nombre': 'MANUEL', 'apellido': 'DUEÑAS', 'documento': None, 'fecha_ing': '2010-01-01', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '20430720', 'telefono': '', 'legajo': '23'}, 'datos_consultados': {'legajo': 23, 'nombre': 'MANUEL', 'apellido': 'DUEÑAS', 'fecha_ing': '2010-01-01', 'tipo_doc': 'DU', 'nro_doc': '20430720', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 19, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 34, 'nombre': 'VICTORIA', 'apellido': 'OCAMPOS', 'documento': None, 'fecha_ing': '2011-01-01', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '26431417', 'telefono': '', 'legajo': '24'}, 'datos_consultados': {'legajo': 24, 'nombre': 'VICTORIA', 'apellido': 'OCAMPOS', 'fecha_ing': '2011-01-01', 'tipo_doc': 'DU', 'nro_doc': '26431417', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 20, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 35, 'nombre': 'FRANCO', 'apellido': 'DE DIOS', 'documento': None, 'fecha_ing': '2010-05-25', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '28834029', 'telefono': '', 'legajo': '25'}, 'datos_consultados': {'legajo': 25, 'nombre': 'FRANCO', 'apellido': 'DE DIOS', 'fecha_ing': '2010-05-25', 'tipo_doc': 'DU', 'nro_doc': '28834029', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 21, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 36, 'nombre': 'ANDRES', 'apellido': 'VARGAS', 'documento': None, 'fecha_ing': '2010-02-15', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '30600633', 'telefono': '', 'legajo': '26'}, 'datos_consultados': {'legajo': 26, 'nombre': 'ANDRES', 'apellido': 'VARGAS', 'fecha_ing': '2010-02-15', 'tipo_doc': 'DU', 'nro_doc': '30600633', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 22, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 37, 'nombre': 'CRISTINA', 'apellido': 'BANEGAS', 'documento': None, 'fecha_ing': '2011-06-15', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '29671270', 'telefono': '', 'legajo': '27'}, 'datos_consultados': {'legajo': 27, 'nombre': 'CRISTINA', 'apellido': 'BANEGAS', 'fecha_ing': '2011-06-15', 'tipo_doc': 'DU', 'nro_doc': '29671270', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 23, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 38, 'nombre': 'VICTORIA', 'apellido': 'CARRERAS', 'documento': None, 'fecha_ing': '2012-02-15', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '35802046', 'telefono': '', 'legajo': '28'}, 'datos_consultados': {'legajo': 28, 'nombre': 'VICTORIA', 'apellido': 'CARRERAS', 'fecha_ing': '2012-02-15', 'tipo_doc': 'DU', 'nro_doc': '35802046', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 24, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 39, 'nombre': 'JUAN', 'apellido': 'CASTRO', 'documento': None, 'fecha_ing': '2013-01-01', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '20368721', 'telefono': '', 'legajo': '29'}, 'datos_consultados': {'legajo': 29, 'nombre': 'JUAN', 'apellido': 'CASTRO', 'fecha_ing': '2013-01-01', 'tipo_doc': 'DU', 'nro_doc': '20368721', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 25, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 40, 'nombre': 'JULIETA', 'apellido': 'GONZALES', 'documento': None, 'fecha_ing': '2013-01-15', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '23250237', 'telefono': '', 'legajo': '30'}, 'datos_consultados': {'legajo': 30, 'nombre': 'JULIETA', 'apellido': 'GONZALES', 'fecha_ing': '2013-01-15', 'tipo_doc': 'DU', 'nro_doc': '23250237', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 26, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 41, 'nombre': 'HORACIO', 'apellido': 'LEGUIZAMON', 'documento': None, 'fecha_ing': '2013-01-20', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc'